module.exports = {
  displayName: 'VaxTrace Backend',
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.spec.ts', '**/*.test.ts'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.{js,ts}',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: [
    'text',
    'lcov',
    'html',
  ],
  moduleNameMapper: {
    '^@vaxtrace/backend/(.*)$': '<rootDir>/$1',
    '^@nestjs/common/(.*)$': '<rootDir>/node_modules/@nestjs/common/$1',
    '^@nestjs/core/(.*)$': '<rootDir>/node_modules/@nestjs/core/$1',
    '^@nestjs/platform-express/(.*)$': '<rootDir>/node_modules/@nestjs/platform-express/$1',
    '^@nestjs/testing/(.*)$': '<rootDir>/node_modules/@nestjs/testing/$1',
    '^@nestjs/config/(.*)$': '<rootDir>/node_modules/@nestjs/config/$1',
    '^@nestjs/jwt/(.*)$': '<rootDir>/node_modules/@nestjs/jwt/$1',
    '^@nestjs/passport/(.*)$': '<rootDir>/node_modules/@nestjs/passport/$1',
    '^@nestjs/typeorm/(.*)$': '<rootDir>/node_modules/@nestjs/typeorm/$1',
    '^@nestjs/schedule/(.*)$': '<rootDir>/node_modules/@nestjs/schedule/$1',
    '^@nestjs/swagger/(.*)$': '<rootDir>/node_modules/@nestjs/swagger/$1',
    '^@nestjs/throttler/(.*)$': '<rootDir>/node_modules/@nestjs/throttler/$1',
    '^@sentry/node/(.*)$': '<rootDir>/node_modules/@sentry/node/$1',
    '^@sentry/tracing/(.*)$': '<rootDir>/node_modules/@sentry/tracing/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  testTimeout: 10000,
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
